// Code generated by go-swagger; DO NOT EDIT.

package contract_transactions_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindContractTransactionsUsingGETHandlerFunc turns a function with the right signature into a find contract transactions using g e t handler
type FindContractTransactionsUsingGETHandlerFunc func(FindContractTransactionsUsingGETParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindContractTransactionsUsingGETHandlerFunc) Handle(params FindContractTransactionsUsingGETParams) middleware.Responder {
	return fn(params)
}

// FindContractTransactionsUsingGETHandler interface for that can handle valid find contract transactions using g e t params
type FindContractTransactionsUsingGETHandler interface {
	Handle(FindContractTransactionsUsingGETParams) middleware.Responder
}

// NewFindContractTransactionsUsingGET creates a new http.Handler for the find contract transactions using g e t operation
func NewFindContractTransactionsUsingGET(ctx *middleware.Context, handler FindContractTransactionsUsingGETHandler) *FindContractTransactionsUsingGET {
	return &FindContractTransactionsUsingGET{Context: ctx, Handler: handler}
}

/* FindContractTransactionsUsingGET swagger:route GET /contracts/{addressHash}/transactions contract-transactions-controller findContractTransactionsUsingGET

Retrieve contract transactions by its address hash.

*/
type FindContractTransactionsUsingGET struct {
	Context *middleware.Context
	Handler FindContractTransactionsUsingGETHandler
}

func (o *FindContractTransactionsUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFindContractTransactionsUsingGETParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
