// Code generated by go-swagger; DO NOT EDIT.

package contract_transactions_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// FindContractTransactionsUsingGETOKCode is the HTTP code returned for type FindContractTransactionsUsingGETOK
const FindContractTransactionsUsingGETOKCode int = 200

/*FindContractTransactionsUsingGETOK OK

swagger:response findContractTransactionsUsingGETOK
*/
type FindContractTransactionsUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.LatestTransactionModel `json:"body,omitempty"`
}

// NewFindContractTransactionsUsingGETOK creates FindContractTransactionsUsingGETOK with default headers values
func NewFindContractTransactionsUsingGETOK() *FindContractTransactionsUsingGETOK {

	return &FindContractTransactionsUsingGETOK{}
}

// WithPayload adds the payload to the find contract transactions using g e t o k response
func (o *FindContractTransactionsUsingGETOK) WithPayload(payload *models.LatestTransactionModel) *FindContractTransactionsUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find contract transactions using g e t o k response
func (o *FindContractTransactionsUsingGETOK) SetPayload(payload *models.LatestTransactionModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindContractTransactionsUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindContractTransactionsUsingGETUnauthorizedCode is the HTTP code returned for type FindContractTransactionsUsingGETUnauthorized
const FindContractTransactionsUsingGETUnauthorizedCode int = 401

/*FindContractTransactionsUsingGETUnauthorized Unauthorized

swagger:response findContractTransactionsUsingGETUnauthorized
*/
type FindContractTransactionsUsingGETUnauthorized struct {
}

// NewFindContractTransactionsUsingGETUnauthorized creates FindContractTransactionsUsingGETUnauthorized with default headers values
func NewFindContractTransactionsUsingGETUnauthorized() *FindContractTransactionsUsingGETUnauthorized {

	return &FindContractTransactionsUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *FindContractTransactionsUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindContractTransactionsUsingGETForbiddenCode is the HTTP code returned for type FindContractTransactionsUsingGETForbidden
const FindContractTransactionsUsingGETForbiddenCode int = 403

/*FindContractTransactionsUsingGETForbidden Forbidden

swagger:response findContractTransactionsUsingGETForbidden
*/
type FindContractTransactionsUsingGETForbidden struct {
}

// NewFindContractTransactionsUsingGETForbidden creates FindContractTransactionsUsingGETForbidden with default headers values
func NewFindContractTransactionsUsingGETForbidden() *FindContractTransactionsUsingGETForbidden {

	return &FindContractTransactionsUsingGETForbidden{}
}

// WriteResponse to the client
func (o *FindContractTransactionsUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindContractTransactionsUsingGETNotFoundCode is the HTTP code returned for type FindContractTransactionsUsingGETNotFound
const FindContractTransactionsUsingGETNotFoundCode int = 404

/*FindContractTransactionsUsingGETNotFound Not Found

swagger:response findContractTransactionsUsingGETNotFound
*/
type FindContractTransactionsUsingGETNotFound struct {
}

// NewFindContractTransactionsUsingGETNotFound creates FindContractTransactionsUsingGETNotFound with default headers values
func NewFindContractTransactionsUsingGETNotFound() *FindContractTransactionsUsingGETNotFound {

	return &FindContractTransactionsUsingGETNotFound{}
}

// WriteResponse to the client
func (o *FindContractTransactionsUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
