// Code generated by go-swagger; DO NOT EDIT.

package block_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// FindBlocksUsingGETOKCode is the HTTP code returned for type FindBlocksUsingGETOK
const FindBlocksUsingGETOKCode int = 200

/*FindBlocksUsingGETOK OK

swagger:response findBlocksUsingGETOK
*/
type FindBlocksUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.LatestBlockModel `json:"body,omitempty"`
}

// NewFindBlocksUsingGETOK creates FindBlocksUsingGETOK with default headers values
func NewFindBlocksUsingGETOK() *FindBlocksUsingGETOK {

	return &FindBlocksUsingGETOK{}
}

// WithPayload adds the payload to the find blocks using g e t o k response
func (o *FindBlocksUsingGETOK) WithPayload(payload *models.LatestBlockModel) *FindBlocksUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find blocks using g e t o k response
func (o *FindBlocksUsingGETOK) SetPayload(payload *models.LatestBlockModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindBlocksUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindBlocksUsingGETUnauthorizedCode is the HTTP code returned for type FindBlocksUsingGETUnauthorized
const FindBlocksUsingGETUnauthorizedCode int = 401

/*FindBlocksUsingGETUnauthorized Unauthorized

swagger:response findBlocksUsingGETUnauthorized
*/
type FindBlocksUsingGETUnauthorized struct {
}

// NewFindBlocksUsingGETUnauthorized creates FindBlocksUsingGETUnauthorized with default headers values
func NewFindBlocksUsingGETUnauthorized() *FindBlocksUsingGETUnauthorized {

	return &FindBlocksUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *FindBlocksUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindBlocksUsingGETForbiddenCode is the HTTP code returned for type FindBlocksUsingGETForbidden
const FindBlocksUsingGETForbiddenCode int = 403

/*FindBlocksUsingGETForbidden Forbidden

swagger:response findBlocksUsingGETForbidden
*/
type FindBlocksUsingGETForbidden struct {
}

// NewFindBlocksUsingGETForbidden creates FindBlocksUsingGETForbidden with default headers values
func NewFindBlocksUsingGETForbidden() *FindBlocksUsingGETForbidden {

	return &FindBlocksUsingGETForbidden{}
}

// WriteResponse to the client
func (o *FindBlocksUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindBlocksUsingGETNotFoundCode is the HTTP code returned for type FindBlocksUsingGETNotFound
const FindBlocksUsingGETNotFoundCode int = 404

/*FindBlocksUsingGETNotFound Not Found

swagger:response findBlocksUsingGETNotFound
*/
type FindBlocksUsingGETNotFound struct {
}

// NewFindBlocksUsingGETNotFound creates FindBlocksUsingGETNotFound with default headers values
func NewFindBlocksUsingGETNotFound() *FindBlocksUsingGETNotFound {

	return &FindBlocksUsingGETNotFound{}
}

// WriteResponse to the client
func (o *FindBlocksUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
