// Code generated by go-swagger; DO NOT EDIT.

package block_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBlockUsingGETHandlerFunc turns a function with the right signature into a get block using g e t handler
type GetBlockUsingGETHandlerFunc func(GetBlockUsingGETParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBlockUsingGETHandlerFunc) Handle(params GetBlockUsingGETParams) middleware.Responder {
	return fn(params)
}

// GetBlockUsingGETHandler interface for that can handle valid get block using g e t params
type GetBlockUsingGETHandler interface {
	Handle(GetBlockUsingGETParams) middleware.Responder
}

// NewGetBlockUsingGET creates a new http.Handler for the get block using g e t operation
func NewGetBlockUsingGET(ctx *middleware.Context, handler GetBlockUsingGETHandler) *GetBlockUsingGET {
	return &GetBlockUsingGET{Context: ctx, Handler: handler}
}

/* GetBlockUsingGET swagger:route GET /blocks/{blockHash} block-controller getBlockUsingGET

Retrieve a block by its hash.

*/
type GetBlockUsingGET struct {
	Context *middleware.Context
	Handler GetBlockUsingGETHandler
}

func (o *GetBlockUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBlockUsingGETParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
