// Code generated by go-swagger; DO NOT EDIT.

package metadata_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteMetadataUsingDELETEOKCode is the HTTP code returned for type DeleteMetadataUsingDELETEOK
const DeleteMetadataUsingDELETEOKCode int = 200

/*DeleteMetadataUsingDELETEOK OK

swagger:response deleteMetadataUsingDELETEOK
*/
type DeleteMetadataUsingDELETEOK struct {
}

// NewDeleteMetadataUsingDELETEOK creates DeleteMetadataUsingDELETEOK with default headers values
func NewDeleteMetadataUsingDELETEOK() *DeleteMetadataUsingDELETEOK {

	return &DeleteMetadataUsingDELETEOK{}
}

// WriteResponse to the client
func (o *DeleteMetadataUsingDELETEOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteMetadataUsingDELETENoContentCode is the HTTP code returned for type DeleteMetadataUsingDELETENoContent
const DeleteMetadataUsingDELETENoContentCode int = 204

/*DeleteMetadataUsingDELETENoContent No Content

swagger:response deleteMetadataUsingDELETENoContent
*/
type DeleteMetadataUsingDELETENoContent struct {
}

// NewDeleteMetadataUsingDELETENoContent creates DeleteMetadataUsingDELETENoContent with default headers values
func NewDeleteMetadataUsingDELETENoContent() *DeleteMetadataUsingDELETENoContent {

	return &DeleteMetadataUsingDELETENoContent{}
}

// WriteResponse to the client
func (o *DeleteMetadataUsingDELETENoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteMetadataUsingDELETEUnauthorizedCode is the HTTP code returned for type DeleteMetadataUsingDELETEUnauthorized
const DeleteMetadataUsingDELETEUnauthorizedCode int = 401

/*DeleteMetadataUsingDELETEUnauthorized Unauthorized

swagger:response deleteMetadataUsingDELETEUnauthorized
*/
type DeleteMetadataUsingDELETEUnauthorized struct {
}

// NewDeleteMetadataUsingDELETEUnauthorized creates DeleteMetadataUsingDELETEUnauthorized with default headers values
func NewDeleteMetadataUsingDELETEUnauthorized() *DeleteMetadataUsingDELETEUnauthorized {

	return &DeleteMetadataUsingDELETEUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteMetadataUsingDELETEUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeleteMetadataUsingDELETEForbiddenCode is the HTTP code returned for type DeleteMetadataUsingDELETEForbidden
const DeleteMetadataUsingDELETEForbiddenCode int = 403

/*DeleteMetadataUsingDELETEForbidden Forbidden

swagger:response deleteMetadataUsingDELETEForbidden
*/
type DeleteMetadataUsingDELETEForbidden struct {
}

// NewDeleteMetadataUsingDELETEForbidden creates DeleteMetadataUsingDELETEForbidden with default headers values
func NewDeleteMetadataUsingDELETEForbidden() *DeleteMetadataUsingDELETEForbidden {

	return &DeleteMetadataUsingDELETEForbidden{}
}

// WriteResponse to the client
func (o *DeleteMetadataUsingDELETEForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
