// Code generated by go-swagger; DO NOT EDIT.

package metadata_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// FindMetadataUsingGETOKCode is the HTTP code returned for type FindMetadataUsingGETOK
const FindMetadataUsingGETOKCode int = 200

/*FindMetadataUsingGETOK OK

swagger:response findMetadataUsingGETOK
*/
type FindMetadataUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListMetadataModel `json:"body,omitempty"`
}

// NewFindMetadataUsingGETOK creates FindMetadataUsingGETOK with default headers values
func NewFindMetadataUsingGETOK() *FindMetadataUsingGETOK {

	return &FindMetadataUsingGETOK{}
}

// WithPayload adds the payload to the find metadata using g e t o k response
func (o *FindMetadataUsingGETOK) WithPayload(payload *models.ListMetadataModel) *FindMetadataUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find metadata using g e t o k response
func (o *FindMetadataUsingGETOK) SetPayload(payload *models.ListMetadataModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindMetadataUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindMetadataUsingGETUnauthorizedCode is the HTTP code returned for type FindMetadataUsingGETUnauthorized
const FindMetadataUsingGETUnauthorizedCode int = 401

/*FindMetadataUsingGETUnauthorized Unauthorized

swagger:response findMetadataUsingGETUnauthorized
*/
type FindMetadataUsingGETUnauthorized struct {
}

// NewFindMetadataUsingGETUnauthorized creates FindMetadataUsingGETUnauthorized with default headers values
func NewFindMetadataUsingGETUnauthorized() *FindMetadataUsingGETUnauthorized {

	return &FindMetadataUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *FindMetadataUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindMetadataUsingGETForbiddenCode is the HTTP code returned for type FindMetadataUsingGETForbidden
const FindMetadataUsingGETForbiddenCode int = 403

/*FindMetadataUsingGETForbidden Forbidden

swagger:response findMetadataUsingGETForbidden
*/
type FindMetadataUsingGETForbidden struct {
}

// NewFindMetadataUsingGETForbidden creates FindMetadataUsingGETForbidden with default headers values
func NewFindMetadataUsingGETForbidden() *FindMetadataUsingGETForbidden {

	return &FindMetadataUsingGETForbidden{}
}

// WriteResponse to the client
func (o *FindMetadataUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindMetadataUsingGETNotFoundCode is the HTTP code returned for type FindMetadataUsingGETNotFound
const FindMetadataUsingGETNotFoundCode int = 404

/*FindMetadataUsingGETNotFound Not Found

swagger:response findMetadataUsingGETNotFound
*/
type FindMetadataUsingGETNotFound struct {
}

// NewFindMetadataUsingGETNotFound creates FindMetadataUsingGETNotFound with default headers values
func NewFindMetadataUsingGETNotFound() *FindMetadataUsingGETNotFound {

	return &FindMetadataUsingGETNotFound{}
}

// WriteResponse to the client
func (o *FindMetadataUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
