// Code generated by go-swagger; DO NOT EDIT.

package metadata_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// UploadMetadataUsingPOSTOKCode is the HTTP code returned for type UploadMetadataUsingPOSTOK
const UploadMetadataUsingPOSTOKCode int = 200

/*UploadMetadataUsingPOSTOK OK

swagger:response uploadMetadataUsingPOSTOK
*/
type UploadMetadataUsingPOSTOK struct {

	/*
	  In: Body
	*/
	Payload *models.MetadataModel `json:"body,omitempty"`
}

// NewUploadMetadataUsingPOSTOK creates UploadMetadataUsingPOSTOK with default headers values
func NewUploadMetadataUsingPOSTOK() *UploadMetadataUsingPOSTOK {

	return &UploadMetadataUsingPOSTOK{}
}

// WithPayload adds the payload to the upload metadata using p o s t o k response
func (o *UploadMetadataUsingPOSTOK) WithPayload(payload *models.MetadataModel) *UploadMetadataUsingPOSTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the upload metadata using p o s t o k response
func (o *UploadMetadataUsingPOSTOK) SetPayload(payload *models.MetadataModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UploadMetadataUsingPOSTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UploadMetadataUsingPOSTCreatedCode is the HTTP code returned for type UploadMetadataUsingPOSTCreated
const UploadMetadataUsingPOSTCreatedCode int = 201

/*UploadMetadataUsingPOSTCreated Created

swagger:response uploadMetadataUsingPOSTCreated
*/
type UploadMetadataUsingPOSTCreated struct {
}

// NewUploadMetadataUsingPOSTCreated creates UploadMetadataUsingPOSTCreated with default headers values
func NewUploadMetadataUsingPOSTCreated() *UploadMetadataUsingPOSTCreated {

	return &UploadMetadataUsingPOSTCreated{}
}

// WriteResponse to the client
func (o *UploadMetadataUsingPOSTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// UploadMetadataUsingPOSTUnauthorizedCode is the HTTP code returned for type UploadMetadataUsingPOSTUnauthorized
const UploadMetadataUsingPOSTUnauthorizedCode int = 401

/*UploadMetadataUsingPOSTUnauthorized Unauthorized

swagger:response uploadMetadataUsingPOSTUnauthorized
*/
type UploadMetadataUsingPOSTUnauthorized struct {
}

// NewUploadMetadataUsingPOSTUnauthorized creates UploadMetadataUsingPOSTUnauthorized with default headers values
func NewUploadMetadataUsingPOSTUnauthorized() *UploadMetadataUsingPOSTUnauthorized {

	return &UploadMetadataUsingPOSTUnauthorized{}
}

// WriteResponse to the client
func (o *UploadMetadataUsingPOSTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// UploadMetadataUsingPOSTForbiddenCode is the HTTP code returned for type UploadMetadataUsingPOSTForbidden
const UploadMetadataUsingPOSTForbiddenCode int = 403

/*UploadMetadataUsingPOSTForbidden Forbidden

swagger:response uploadMetadataUsingPOSTForbidden
*/
type UploadMetadataUsingPOSTForbidden struct {
}

// NewUploadMetadataUsingPOSTForbidden creates UploadMetadataUsingPOSTForbidden with default headers values
func NewUploadMetadataUsingPOSTForbidden() *UploadMetadataUsingPOSTForbidden {

	return &UploadMetadataUsingPOSTForbidden{}
}

// WriteResponse to the client
func (o *UploadMetadataUsingPOSTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// UploadMetadataUsingPOSTNotFoundCode is the HTTP code returned for type UploadMetadataUsingPOSTNotFound
const UploadMetadataUsingPOSTNotFoundCode int = 404

/*UploadMetadataUsingPOSTNotFound Not Found

swagger:response uploadMetadataUsingPOSTNotFound
*/
type UploadMetadataUsingPOSTNotFound struct {
}

// NewUploadMetadataUsingPOSTNotFound creates UploadMetadataUsingPOSTNotFound with default headers values
func NewUploadMetadataUsingPOSTNotFound() *UploadMetadataUsingPOSTNotFound {

	return &UploadMetadataUsingPOSTNotFound{}
}

// WriteResponse to the client
func (o *UploadMetadataUsingPOSTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
