// Code generated by go-swagger; DO NOT EDIT.

package search_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SearchUsingGETHandlerFunc turns a function with the right signature into a search using g e t handler
type SearchUsingGETHandlerFunc func(SearchUsingGETParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SearchUsingGETHandlerFunc) Handle(params SearchUsingGETParams) middleware.Responder {
	return fn(params)
}

// SearchUsingGETHandler interface for that can handle valid search using g e t params
type SearchUsingGETHandler interface {
	Handle(SearchUsingGETParams) middleware.Responder
}

// NewSearchUsingGET creates a new http.Handler for the search using g e t operation
func NewSearchUsingGET(ctx *middleware.Context, handler SearchUsingGETHandler) *SearchUsingGET {
	return &SearchUsingGET{Context: ctx, Handler: handler}
}

/* SearchUsingGET swagger:route GET /search search-controller searchUsingGET

Retrieve blocks, transactions, accounts by hash.

*/
type SearchUsingGET struct {
	Context *middleware.Context
	Handler SearchUsingGETHandler
}

func (o *SearchUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSearchUsingGETParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
