// Code generated by go-swagger; DO NOT EDIT.

package search_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// SearchUsingGETOKCode is the HTTP code returned for type SearchUsingGETOK
const SearchUsingGETOKCode int = 200

/*SearchUsingGETOK OK

swagger:response searchUsingGETOK
*/
type SearchUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListSearchResultModel `json:"body,omitempty"`
}

// NewSearchUsingGETOK creates SearchUsingGETOK with default headers values
func NewSearchUsingGETOK() *SearchUsingGETOK {

	return &SearchUsingGETOK{}
}

// WithPayload adds the payload to the search using g e t o k response
func (o *SearchUsingGETOK) WithPayload(payload *models.ListSearchResultModel) *SearchUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search using g e t o k response
func (o *SearchUsingGETOK) SetPayload(payload *models.ListSearchResultModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SearchUsingGETUnauthorizedCode is the HTTP code returned for type SearchUsingGETUnauthorized
const SearchUsingGETUnauthorizedCode int = 401

/*SearchUsingGETUnauthorized Unauthorized

swagger:response searchUsingGETUnauthorized
*/
type SearchUsingGETUnauthorized struct {
}

// NewSearchUsingGETUnauthorized creates SearchUsingGETUnauthorized with default headers values
func NewSearchUsingGETUnauthorized() *SearchUsingGETUnauthorized {

	return &SearchUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *SearchUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// SearchUsingGETForbiddenCode is the HTTP code returned for type SearchUsingGETForbidden
const SearchUsingGETForbiddenCode int = 403

/*SearchUsingGETForbidden Forbidden

swagger:response searchUsingGETForbidden
*/
type SearchUsingGETForbidden struct {
}

// NewSearchUsingGETForbidden creates SearchUsingGETForbidden with default headers values
func NewSearchUsingGETForbidden() *SearchUsingGETForbidden {

	return &SearchUsingGETForbidden{}
}

// WriteResponse to the client
func (o *SearchUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// SearchUsingGETNotFoundCode is the HTTP code returned for type SearchUsingGETNotFound
const SearchUsingGETNotFoundCode int = 404

/*SearchUsingGETNotFound Not Found

swagger:response searchUsingGETNotFound
*/
type SearchUsingGETNotFound struct {
}

// NewSearchUsingGETNotFound creates SearchUsingGETNotFound with default headers values
func NewSearchUsingGETNotFound() *SearchUsingGETNotFound {

	return &SearchUsingGETNotFound{}
}

// WriteResponse to the client
func (o *SearchUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
