// Code generated by go-swagger; DO NOT EDIT.

package search_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// SearchUsingGET1OKCode is the HTTP code returned for type SearchUsingGET1OK
const SearchUsingGET1OKCode int = 200

/*SearchUsingGET1OK OK

swagger:response searchUsingGET1OK
*/
type SearchUsingGET1OK struct {

	/*
	  In: Body
	*/
	Payload *models.ListSearchResultModel `json:"body,omitempty"`
}

// NewSearchUsingGET1OK creates SearchUsingGET1OK with default headers values
func NewSearchUsingGET1OK() *SearchUsingGET1OK {

	return &SearchUsingGET1OK{}
}

// WithPayload adds the payload to the search using g e t1 o k response
func (o *SearchUsingGET1OK) WithPayload(payload *models.ListSearchResultModel) *SearchUsingGET1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search using g e t1 o k response
func (o *SearchUsingGET1OK) SetPayload(payload *models.ListSearchResultModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchUsingGET1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SearchUsingGET1UnauthorizedCode is the HTTP code returned for type SearchUsingGET1Unauthorized
const SearchUsingGET1UnauthorizedCode int = 401

/*SearchUsingGET1Unauthorized Unauthorized

swagger:response searchUsingGET1Unauthorized
*/
type SearchUsingGET1Unauthorized struct {
}

// NewSearchUsingGET1Unauthorized creates SearchUsingGET1Unauthorized with default headers values
func NewSearchUsingGET1Unauthorized() *SearchUsingGET1Unauthorized {

	return &SearchUsingGET1Unauthorized{}
}

// WriteResponse to the client
func (o *SearchUsingGET1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// SearchUsingGET1ForbiddenCode is the HTTP code returned for type SearchUsingGET1Forbidden
const SearchUsingGET1ForbiddenCode int = 403

/*SearchUsingGET1Forbidden Forbidden

swagger:response searchUsingGET1Forbidden
*/
type SearchUsingGET1Forbidden struct {
}

// NewSearchUsingGET1Forbidden creates SearchUsingGET1Forbidden with default headers values
func NewSearchUsingGET1Forbidden() *SearchUsingGET1Forbidden {

	return &SearchUsingGET1Forbidden{}
}

// WriteResponse to the client
func (o *SearchUsingGET1Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// SearchUsingGET1NotFoundCode is the HTTP code returned for type SearchUsingGET1NotFound
const SearchUsingGET1NotFoundCode int = 404

/*SearchUsingGET1NotFound Not Found

swagger:response searchUsingGET1NotFound
*/
type SearchUsingGET1NotFound struct {
}

// NewSearchUsingGET1NotFound creates SearchUsingGET1NotFound with default headers values
func NewSearchUsingGET1NotFound() *SearchUsingGET1NotFound {

	return &SearchUsingGET1NotFound{}
}

// WriteResponse to the client
func (o *SearchUsingGET1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
