// Code generated by go-swagger; DO NOT EDIT.

package search_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewSearchUsingGET1Params creates a new SearchUsingGET1Params object
//
// There are no default values defined in the spec.
func NewSearchUsingGET1Params() SearchUsingGET1Params {

	return SearchUsingGET1Params{}
}

// SearchUsingGET1Params contains all the bound params for the search using g e t 1 operation
// typically these are obtained from a http.Request
//
// swagger:parameters searchUsingGET_1
type SearchUsingGET1Params struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The search query string.
	  In: query
	*/
	Query *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSearchUsingGET1Params() beforehand.
func (o *SearchUsingGET1Params) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qQuery, qhkQuery, _ := qs.GetOK("query")
	if err := o.bindQuery(qQuery, qhkQuery, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindQuery binds and validates parameter Query from query.
func (o *SearchUsingGET1Params) bindQuery(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Query = &raw

	return nil
}
