// Code generated by go-swagger; DO NOT EDIT.

package configuration_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// FrontendConfigurationUsingGETOKCode is the HTTP code returned for type FrontendConfigurationUsingGETOK
const FrontendConfigurationUsingGETOKCode int = 200

/*FrontendConfigurationUsingGETOK OK

swagger:response frontendConfigurationUsingGETOK
*/
type FrontendConfigurationUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.EpirusConfigurationModel `json:"body,omitempty"`
}

// NewFrontendConfigurationUsingGETOK creates FrontendConfigurationUsingGETOK with default headers values
func NewFrontendConfigurationUsingGETOK() *FrontendConfigurationUsingGETOK {

	return &FrontendConfigurationUsingGETOK{}
}

// WithPayload adds the payload to the frontend configuration using g e t o k response
func (o *FrontendConfigurationUsingGETOK) WithPayload(payload *models.EpirusConfigurationModel) *FrontendConfigurationUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the frontend configuration using g e t o k response
func (o *FrontendConfigurationUsingGETOK) SetPayload(payload *models.EpirusConfigurationModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FrontendConfigurationUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FrontendConfigurationUsingGETUnauthorizedCode is the HTTP code returned for type FrontendConfigurationUsingGETUnauthorized
const FrontendConfigurationUsingGETUnauthorizedCode int = 401

/*FrontendConfigurationUsingGETUnauthorized Unauthorized

swagger:response frontendConfigurationUsingGETUnauthorized
*/
type FrontendConfigurationUsingGETUnauthorized struct {
}

// NewFrontendConfigurationUsingGETUnauthorized creates FrontendConfigurationUsingGETUnauthorized with default headers values
func NewFrontendConfigurationUsingGETUnauthorized() *FrontendConfigurationUsingGETUnauthorized {

	return &FrontendConfigurationUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *FrontendConfigurationUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FrontendConfigurationUsingGETForbiddenCode is the HTTP code returned for type FrontendConfigurationUsingGETForbidden
const FrontendConfigurationUsingGETForbiddenCode int = 403

/*FrontendConfigurationUsingGETForbidden Forbidden

swagger:response frontendConfigurationUsingGETForbidden
*/
type FrontendConfigurationUsingGETForbidden struct {
}

// NewFrontendConfigurationUsingGETForbidden creates FrontendConfigurationUsingGETForbidden with default headers values
func NewFrontendConfigurationUsingGETForbidden() *FrontendConfigurationUsingGETForbidden {

	return &FrontendConfigurationUsingGETForbidden{}
}

// WriteResponse to the client
func (o *FrontendConfigurationUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FrontendConfigurationUsingGETNotFoundCode is the HTTP code returned for type FrontendConfigurationUsingGETNotFound
const FrontendConfigurationUsingGETNotFoundCode int = 404

/*FrontendConfigurationUsingGETNotFound Not Found

swagger:response frontendConfigurationUsingGETNotFound
*/
type FrontendConfigurationUsingGETNotFound struct {
}

// NewFrontendConfigurationUsingGETNotFound creates FrontendConfigurationUsingGETNotFound with default headers values
func NewFrontendConfigurationUsingGETNotFound() *FrontendConfigurationUsingGETNotFound {

	return &FrontendConfigurationUsingGETNotFound{}
}

// WriteResponse to the client
func (o *FrontendConfigurationUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
