// Code generated by go-swagger; DO NOT EDIT.

package transaction_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindTransactionsUsingGETHandlerFunc turns a function with the right signature into a find transactions using g e t handler
type FindTransactionsUsingGETHandlerFunc func(FindTransactionsUsingGETParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindTransactionsUsingGETHandlerFunc) Handle(params FindTransactionsUsingGETParams) middleware.Responder {
	return fn(params)
}

// FindTransactionsUsingGETHandler interface for that can handle valid find transactions using g e t params
type FindTransactionsUsingGETHandler interface {
	Handle(FindTransactionsUsingGETParams) middleware.Responder
}

// NewFindTransactionsUsingGET creates a new http.Handler for the find transactions using g e t operation
func NewFindTransactionsUsingGET(ctx *middleware.Context, handler FindTransactionsUsingGETHandler) *FindTransactionsUsingGET {
	return &FindTransactionsUsingGET{Context: ctx, Handler: handler}
}

/* FindTransactionsUsingGET swagger:route GET /transactions transaction-controller findTransactionsUsingGET

Retrieve transactions by address or block.

*/
type FindTransactionsUsingGET struct {
	Context *middleware.Context
	Handler FindTransactionsUsingGETHandler
}

func (o *FindTransactionsUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFindTransactionsUsingGETParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
