// Code generated by go-swagger; DO NOT EDIT.

package transaction_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTransactionUsingGETHandlerFunc turns a function with the right signature into a get transaction using g e t handler
type GetTransactionUsingGETHandlerFunc func(GetTransactionUsingGETParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTransactionUsingGETHandlerFunc) Handle(params GetTransactionUsingGETParams) middleware.Responder {
	return fn(params)
}

// GetTransactionUsingGETHandler interface for that can handle valid get transaction using g e t params
type GetTransactionUsingGETHandler interface {
	Handle(GetTransactionUsingGETParams) middleware.Responder
}

// NewGetTransactionUsingGET creates a new http.Handler for the get transaction using g e t operation
func NewGetTransactionUsingGET(ctx *middleware.Context, handler GetTransactionUsingGETHandler) *GetTransactionUsingGET {
	return &GetTransactionUsingGET{Context: ctx, Handler: handler}
}

/* GetTransactionUsingGET swagger:route GET /transactions/{transactionHash} transaction-controller getTransactionUsingGET

Retrieve a transaction by its hash.

*/
type GetTransactionUsingGET struct {
	Context *middleware.Context
	Handler GetTransactionUsingGETHandler
}

func (o *GetTransactionUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTransactionUsingGETParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
