// Code generated by go-swagger; DO NOT EDIT.

package transaction_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// GetTransactionUsingGETOKCode is the HTTP code returned for type GetTransactionUsingGETOK
const GetTransactionUsingGETOKCode int = 200

/*GetTransactionUsingGETOK OK

swagger:response getTransactionUsingGETOK
*/
type GetTransactionUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.TransactionModel `json:"body,omitempty"`
}

// NewGetTransactionUsingGETOK creates GetTransactionUsingGETOK with default headers values
func NewGetTransactionUsingGETOK() *GetTransactionUsingGETOK {

	return &GetTransactionUsingGETOK{}
}

// WithPayload adds the payload to the get transaction using g e t o k response
func (o *GetTransactionUsingGETOK) WithPayload(payload *models.TransactionModel) *GetTransactionUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transaction using g e t o k response
func (o *GetTransactionUsingGETOK) SetPayload(payload *models.TransactionModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransactionUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTransactionUsingGETUnauthorizedCode is the HTTP code returned for type GetTransactionUsingGETUnauthorized
const GetTransactionUsingGETUnauthorizedCode int = 401

/*GetTransactionUsingGETUnauthorized Unauthorized

swagger:response getTransactionUsingGETUnauthorized
*/
type GetTransactionUsingGETUnauthorized struct {
}

// NewGetTransactionUsingGETUnauthorized creates GetTransactionUsingGETUnauthorized with default headers values
func NewGetTransactionUsingGETUnauthorized() *GetTransactionUsingGETUnauthorized {

	return &GetTransactionUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *GetTransactionUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetTransactionUsingGETForbiddenCode is the HTTP code returned for type GetTransactionUsingGETForbidden
const GetTransactionUsingGETForbiddenCode int = 403

/*GetTransactionUsingGETForbidden Forbidden

swagger:response getTransactionUsingGETForbidden
*/
type GetTransactionUsingGETForbidden struct {
}

// NewGetTransactionUsingGETForbidden creates GetTransactionUsingGETForbidden with default headers values
func NewGetTransactionUsingGETForbidden() *GetTransactionUsingGETForbidden {

	return &GetTransactionUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetTransactionUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetTransactionUsingGETNotFoundCode is the HTTP code returned for type GetTransactionUsingGETNotFound
const GetTransactionUsingGETNotFoundCode int = 404

/*GetTransactionUsingGETNotFound Not Found

swagger:response getTransactionUsingGETNotFound
*/
type GetTransactionUsingGETNotFound struct {
}

// NewGetTransactionUsingGETNotFound creates GetTransactionUsingGETNotFound with default headers values
func NewGetTransactionUsingGETNotFound() *GetTransactionUsingGETNotFound {

	return &GetTransactionUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetTransactionUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
