// Code generated by go-swagger; DO NOT EDIT.

package transaction_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetTransactionUsingGETParams creates a new GetTransactionUsingGETParams object
//
// There are no default values defined in the spec.
func NewGetTransactionUsingGETParams() GetTransactionUsingGETParams {

	return GetTransactionUsingGETParams{}
}

// GetTransactionUsingGETParams contains all the bound params for the get transaction using g e t operation
// typically these are obtained from a http.Request
//
// swagger:parameters getTransactionUsingGET
type GetTransactionUsingGETParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The hash identifying the transaction.
	  In: path
	*/
	TransactionHash *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTransactionUsingGETParams() beforehand.
func (o *GetTransactionUsingGETParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rTransactionHash, rhkTransactionHash, _ := route.Params.GetOK("transactionHash")
	if err := o.bindTransactionHash(rTransactionHash, rhkTransactionHash, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTransactionHash binds and validates parameter TransactionHash from path.
func (o *GetTransactionUsingGETParams) bindTransactionHash(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// Parameter is provided by construction from the route
	o.TransactionHash = &raw

	return nil
}
