// Code generated by go-swagger; DO NOT EDIT.

package dashboard_transactions_totals_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// GetTotalsUsingGET1OKCode is the HTTP code returned for type GetTotalsUsingGET1OK
const GetTotalsUsingGET1OKCode int = 200

/*GetTotalsUsingGET1OK OK

swagger:response getTotalsUsingGET1OK
*/
type GetTotalsUsingGET1OK struct {

	/*
	  In: Body
	*/
	Payload *models.DashboardTotalsModel `json:"body,omitempty"`
}

// NewGetTotalsUsingGET1OK creates GetTotalsUsingGET1OK with default headers values
func NewGetTotalsUsingGET1OK() *GetTotalsUsingGET1OK {

	return &GetTotalsUsingGET1OK{}
}

// WithPayload adds the payload to the get totals using g e t1 o k response
func (o *GetTotalsUsingGET1OK) WithPayload(payload *models.DashboardTotalsModel) *GetTotalsUsingGET1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get totals using g e t1 o k response
func (o *GetTotalsUsingGET1OK) SetPayload(payload *models.DashboardTotalsModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTotalsUsingGET1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTotalsUsingGET1UnauthorizedCode is the HTTP code returned for type GetTotalsUsingGET1Unauthorized
const GetTotalsUsingGET1UnauthorizedCode int = 401

/*GetTotalsUsingGET1Unauthorized Unauthorized

swagger:response getTotalsUsingGET1Unauthorized
*/
type GetTotalsUsingGET1Unauthorized struct {
}

// NewGetTotalsUsingGET1Unauthorized creates GetTotalsUsingGET1Unauthorized with default headers values
func NewGetTotalsUsingGET1Unauthorized() *GetTotalsUsingGET1Unauthorized {

	return &GetTotalsUsingGET1Unauthorized{}
}

// WriteResponse to the client
func (o *GetTotalsUsingGET1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetTotalsUsingGET1ForbiddenCode is the HTTP code returned for type GetTotalsUsingGET1Forbidden
const GetTotalsUsingGET1ForbiddenCode int = 403

/*GetTotalsUsingGET1Forbidden Forbidden

swagger:response getTotalsUsingGET1Forbidden
*/
type GetTotalsUsingGET1Forbidden struct {
}

// NewGetTotalsUsingGET1Forbidden creates GetTotalsUsingGET1Forbidden with default headers values
func NewGetTotalsUsingGET1Forbidden() *GetTotalsUsingGET1Forbidden {

	return &GetTotalsUsingGET1Forbidden{}
}

// WriteResponse to the client
func (o *GetTotalsUsingGET1Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetTotalsUsingGET1NotFoundCode is the HTTP code returned for type GetTotalsUsingGET1NotFound
const GetTotalsUsingGET1NotFoundCode int = 404

/*GetTotalsUsingGET1NotFound Not Found

swagger:response getTotalsUsingGET1NotFound
*/
type GetTotalsUsingGET1NotFound struct {
}

// NewGetTotalsUsingGET1NotFound creates GetTotalsUsingGET1NotFound with default headers values
func NewGetTotalsUsingGET1NotFound() *GetTotalsUsingGET1NotFound {

	return &GetTotalsUsingGET1NotFound{}
}

// WriteResponse to the client
func (o *GetTotalsUsingGET1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
