// Code generated by go-swagger; DO NOT EDIT.

package dashboard_transactions_totals_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTotalsUsingGETHandlerFunc turns a function with the right signature into a get totals using g e t handler
type GetTotalsUsingGETHandlerFunc func(GetTotalsUsingGETParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTotalsUsingGETHandlerFunc) Handle(params GetTotalsUsingGETParams) middleware.Responder {
	return fn(params)
}

// GetTotalsUsingGETHandler interface for that can handle valid get totals using g e t params
type GetTotalsUsingGETHandler interface {
	Handle(GetTotalsUsingGETParams) middleware.Responder
}

// NewGetTotalsUsingGET creates a new http.Handler for the get totals using g e t operation
func NewGetTotalsUsingGET(ctx *middleware.Context, handler GetTotalsUsingGETHandler) *GetTotalsUsingGET {
	return &GetTotalsUsingGET{Context: ctx, Handler: handler}
}

/* GetTotalsUsingGET swagger:route GET /dashboard/transactions/totals/{period} dashboard-transactions-totals-controller getTotalsUsingGET

Retrieve total number of different transactions types

*/
type GetTotalsUsingGET struct {
	Context *middleware.Context
	Handler GetTotalsUsingGETHandler
}

func (o *GetTotalsUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTotalsUsingGETParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
