// Code generated by go-swagger; DO NOT EDIT.

package dashboard_transactions_totals_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// GetTotalsUsingGETOKCode is the HTTP code returned for type GetTotalsUsingGETOK
const GetTotalsUsingGETOKCode int = 200

/*GetTotalsUsingGETOK OK

swagger:response getTotalsUsingGETOK
*/
type GetTotalsUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.DashboardTimeseriesTotalsModel `json:"body,omitempty"`
}

// NewGetTotalsUsingGETOK creates GetTotalsUsingGETOK with default headers values
func NewGetTotalsUsingGETOK() *GetTotalsUsingGETOK {

	return &GetTotalsUsingGETOK{}
}

// WithPayload adds the payload to the get totals using g e t o k response
func (o *GetTotalsUsingGETOK) WithPayload(payload *models.DashboardTimeseriesTotalsModel) *GetTotalsUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get totals using g e t o k response
func (o *GetTotalsUsingGETOK) SetPayload(payload *models.DashboardTimeseriesTotalsModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTotalsUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTotalsUsingGETUnauthorizedCode is the HTTP code returned for type GetTotalsUsingGETUnauthorized
const GetTotalsUsingGETUnauthorizedCode int = 401

/*GetTotalsUsingGETUnauthorized Unauthorized

swagger:response getTotalsUsingGETUnauthorized
*/
type GetTotalsUsingGETUnauthorized struct {
}

// NewGetTotalsUsingGETUnauthorized creates GetTotalsUsingGETUnauthorized with default headers values
func NewGetTotalsUsingGETUnauthorized() *GetTotalsUsingGETUnauthorized {

	return &GetTotalsUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *GetTotalsUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetTotalsUsingGETForbiddenCode is the HTTP code returned for type GetTotalsUsingGETForbidden
const GetTotalsUsingGETForbiddenCode int = 403

/*GetTotalsUsingGETForbidden Forbidden

swagger:response getTotalsUsingGETForbidden
*/
type GetTotalsUsingGETForbidden struct {
}

// NewGetTotalsUsingGETForbidden creates GetTotalsUsingGETForbidden with default headers values
func NewGetTotalsUsingGETForbidden() *GetTotalsUsingGETForbidden {

	return &GetTotalsUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetTotalsUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetTotalsUsingGETNotFoundCode is the HTTP code returned for type GetTotalsUsingGETNotFound
const GetTotalsUsingGETNotFoundCode int = 404

/*GetTotalsUsingGETNotFound Not Found

swagger:response getTotalsUsingGETNotFound
*/
type GetTotalsUsingGETNotFound struct {
}

// NewGetTotalsUsingGETNotFound creates GetTotalsUsingGETNotFound with default headers values
func NewGetTotalsUsingGETNotFound() *GetTotalsUsingGETNotFound {

	return &GetTotalsUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetTotalsUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
