// Code generated by go-swagger; DO NOT EDIT.

package account_mapping_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddAccountUsingPOSTOKCode is the HTTP code returned for type AddAccountUsingPOSTOK
const AddAccountUsingPOSTOKCode int = 200

/*AddAccountUsingPOSTOK OK

swagger:response addAccountUsingPOSTOK
*/
type AddAccountUsingPOSTOK struct {
}

// NewAddAccountUsingPOSTOK creates AddAccountUsingPOSTOK with default headers values
func NewAddAccountUsingPOSTOK() *AddAccountUsingPOSTOK {

	return &AddAccountUsingPOSTOK{}
}

// WriteResponse to the client
func (o *AddAccountUsingPOSTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AddAccountUsingPOSTCreatedCode is the HTTP code returned for type AddAccountUsingPOSTCreated
const AddAccountUsingPOSTCreatedCode int = 201

/*AddAccountUsingPOSTCreated Created

swagger:response addAccountUsingPOSTCreated
*/
type AddAccountUsingPOSTCreated struct {
}

// NewAddAccountUsingPOSTCreated creates AddAccountUsingPOSTCreated with default headers values
func NewAddAccountUsingPOSTCreated() *AddAccountUsingPOSTCreated {

	return &AddAccountUsingPOSTCreated{}
}

// WriteResponse to the client
func (o *AddAccountUsingPOSTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddAccountUsingPOSTUnauthorizedCode is the HTTP code returned for type AddAccountUsingPOSTUnauthorized
const AddAccountUsingPOSTUnauthorizedCode int = 401

/*AddAccountUsingPOSTUnauthorized Unauthorized

swagger:response addAccountUsingPOSTUnauthorized
*/
type AddAccountUsingPOSTUnauthorized struct {
}

// NewAddAccountUsingPOSTUnauthorized creates AddAccountUsingPOSTUnauthorized with default headers values
func NewAddAccountUsingPOSTUnauthorized() *AddAccountUsingPOSTUnauthorized {

	return &AddAccountUsingPOSTUnauthorized{}
}

// WriteResponse to the client
func (o *AddAccountUsingPOSTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// AddAccountUsingPOSTForbiddenCode is the HTTP code returned for type AddAccountUsingPOSTForbidden
const AddAccountUsingPOSTForbiddenCode int = 403

/*AddAccountUsingPOSTForbidden Forbidden

swagger:response addAccountUsingPOSTForbidden
*/
type AddAccountUsingPOSTForbidden struct {
}

// NewAddAccountUsingPOSTForbidden creates AddAccountUsingPOSTForbidden with default headers values
func NewAddAccountUsingPOSTForbidden() *AddAccountUsingPOSTForbidden {

	return &AddAccountUsingPOSTForbidden{}
}

// WriteResponse to the client
func (o *AddAccountUsingPOSTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// AddAccountUsingPOSTNotFoundCode is the HTTP code returned for type AddAccountUsingPOSTNotFound
const AddAccountUsingPOSTNotFoundCode int = 404

/*AddAccountUsingPOSTNotFound Not Found

swagger:response addAccountUsingPOSTNotFound
*/
type AddAccountUsingPOSTNotFound struct {
}

// NewAddAccountUsingPOSTNotFound creates AddAccountUsingPOSTNotFound with default headers values
func NewAddAccountUsingPOSTNotFound() *AddAccountUsingPOSTNotFound {

	return &AddAccountUsingPOSTNotFound{}
}

// WriteResponse to the client
func (o *AddAccountUsingPOSTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
