// Code generated by go-swagger; DO NOT EDIT.

package account_mapping_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteAccountUsingDELETEOKCode is the HTTP code returned for type DeleteAccountUsingDELETEOK
const DeleteAccountUsingDELETEOKCode int = 200

/*DeleteAccountUsingDELETEOK OK

swagger:response deleteAccountUsingDELETEOK
*/
type DeleteAccountUsingDELETEOK struct {
}

// NewDeleteAccountUsingDELETEOK creates DeleteAccountUsingDELETEOK with default headers values
func NewDeleteAccountUsingDELETEOK() *DeleteAccountUsingDELETEOK {

	return &DeleteAccountUsingDELETEOK{}
}

// WriteResponse to the client
func (o *DeleteAccountUsingDELETEOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteAccountUsingDELETENoContentCode is the HTTP code returned for type DeleteAccountUsingDELETENoContent
const DeleteAccountUsingDELETENoContentCode int = 204

/*DeleteAccountUsingDELETENoContent No Content

swagger:response deleteAccountUsingDELETENoContent
*/
type DeleteAccountUsingDELETENoContent struct {
}

// NewDeleteAccountUsingDELETENoContent creates DeleteAccountUsingDELETENoContent with default headers values
func NewDeleteAccountUsingDELETENoContent() *DeleteAccountUsingDELETENoContent {

	return &DeleteAccountUsingDELETENoContent{}
}

// WriteResponse to the client
func (o *DeleteAccountUsingDELETENoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteAccountUsingDELETEUnauthorizedCode is the HTTP code returned for type DeleteAccountUsingDELETEUnauthorized
const DeleteAccountUsingDELETEUnauthorizedCode int = 401

/*DeleteAccountUsingDELETEUnauthorized Unauthorized

swagger:response deleteAccountUsingDELETEUnauthorized
*/
type DeleteAccountUsingDELETEUnauthorized struct {
}

// NewDeleteAccountUsingDELETEUnauthorized creates DeleteAccountUsingDELETEUnauthorized with default headers values
func NewDeleteAccountUsingDELETEUnauthorized() *DeleteAccountUsingDELETEUnauthorized {

	return &DeleteAccountUsingDELETEUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteAccountUsingDELETEUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeleteAccountUsingDELETEForbiddenCode is the HTTP code returned for type DeleteAccountUsingDELETEForbidden
const DeleteAccountUsingDELETEForbiddenCode int = 403

/*DeleteAccountUsingDELETEForbidden Forbidden

swagger:response deleteAccountUsingDELETEForbidden
*/
type DeleteAccountUsingDELETEForbidden struct {
}

// NewDeleteAccountUsingDELETEForbidden creates DeleteAccountUsingDELETEForbidden with default headers values
func NewDeleteAccountUsingDELETEForbidden() *DeleteAccountUsingDELETEForbidden {

	return &DeleteAccountUsingDELETEForbidden{}
}

// WriteResponse to the client
func (o *DeleteAccountUsingDELETEForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
