// Code generated by go-swagger; DO NOT EDIT.

package account_mapping_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// EditAccountUsingPUTOKCode is the HTTP code returned for type EditAccountUsingPUTOK
const EditAccountUsingPUTOKCode int = 200

/*EditAccountUsingPUTOK OK

swagger:response editAccountUsingPUTOK
*/
type EditAccountUsingPUTOK struct {
}

// NewEditAccountUsingPUTOK creates EditAccountUsingPUTOK with default headers values
func NewEditAccountUsingPUTOK() *EditAccountUsingPUTOK {

	return &EditAccountUsingPUTOK{}
}

// WriteResponse to the client
func (o *EditAccountUsingPUTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// EditAccountUsingPUTCreatedCode is the HTTP code returned for type EditAccountUsingPUTCreated
const EditAccountUsingPUTCreatedCode int = 201

/*EditAccountUsingPUTCreated Created

swagger:response editAccountUsingPUTCreated
*/
type EditAccountUsingPUTCreated struct {
}

// NewEditAccountUsingPUTCreated creates EditAccountUsingPUTCreated with default headers values
func NewEditAccountUsingPUTCreated() *EditAccountUsingPUTCreated {

	return &EditAccountUsingPUTCreated{}
}

// WriteResponse to the client
func (o *EditAccountUsingPUTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// EditAccountUsingPUTUnauthorizedCode is the HTTP code returned for type EditAccountUsingPUTUnauthorized
const EditAccountUsingPUTUnauthorizedCode int = 401

/*EditAccountUsingPUTUnauthorized Unauthorized

swagger:response editAccountUsingPUTUnauthorized
*/
type EditAccountUsingPUTUnauthorized struct {
}

// NewEditAccountUsingPUTUnauthorized creates EditAccountUsingPUTUnauthorized with default headers values
func NewEditAccountUsingPUTUnauthorized() *EditAccountUsingPUTUnauthorized {

	return &EditAccountUsingPUTUnauthorized{}
}

// WriteResponse to the client
func (o *EditAccountUsingPUTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// EditAccountUsingPUTForbiddenCode is the HTTP code returned for type EditAccountUsingPUTForbidden
const EditAccountUsingPUTForbiddenCode int = 403

/*EditAccountUsingPUTForbidden Forbidden

swagger:response editAccountUsingPUTForbidden
*/
type EditAccountUsingPUTForbidden struct {
}

// NewEditAccountUsingPUTForbidden creates EditAccountUsingPUTForbidden with default headers values
func NewEditAccountUsingPUTForbidden() *EditAccountUsingPUTForbidden {

	return &EditAccountUsingPUTForbidden{}
}

// WriteResponse to the client
func (o *EditAccountUsingPUTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// EditAccountUsingPUTNotFoundCode is the HTTP code returned for type EditAccountUsingPUTNotFound
const EditAccountUsingPUTNotFoundCode int = 404

/*EditAccountUsingPUTNotFound Not Found

swagger:response editAccountUsingPUTNotFound
*/
type EditAccountUsingPUTNotFound struct {
}

// NewEditAccountUsingPUTNotFound creates EditAccountUsingPUTNotFound with default headers values
func NewEditAccountUsingPUTNotFound() *EditAccountUsingPUTNotFound {

	return &EditAccountUsingPUTNotFound{}
}

// WriteResponse to the client
func (o *EditAccountUsingPUTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
