// Code generated by go-swagger; DO NOT EDIT.

package account_mapping_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// EditAccountUsingPUTHandlerFunc turns a function with the right signature into a edit account using p u t handler
type EditAccountUsingPUTHandlerFunc func(EditAccountUsingPUTParams) middleware.Responder

// Handle executing the request and returning a response
func (fn EditAccountUsingPUTHandlerFunc) Handle(params EditAccountUsingPUTParams) middleware.Responder {
	return fn(params)
}

// EditAccountUsingPUTHandler interface for that can handle valid edit account using p u t params
type EditAccountUsingPUTHandler interface {
	Handle(EditAccountUsingPUTParams) middleware.Responder
}

// NewEditAccountUsingPUT creates a new http.Handler for the edit account using p u t operation
func NewEditAccountUsingPUT(ctx *middleware.Context, handler EditAccountUsingPUTHandler) *EditAccountUsingPUT {
	return &EditAccountUsingPUT{Context: ctx, Handler: handler}
}

/* EditAccountUsingPUT swagger:route PUT /mappings/{id} account-mapping-controller editAccountUsingPUT

Edit account with corresponding address and label

*/
type EditAccountUsingPUT struct {
	Context *middleware.Context
	Handler EditAccountUsingPUTHandler
}

func (o *EditAccountUsingPUT) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewEditAccountUsingPUTParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
