// Code generated by go-swagger; DO NOT EDIT.

package account_mapping_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// FindAccountsUsingGETOKCode is the HTTP code returned for type FindAccountsUsingGETOK
const FindAccountsUsingGETOKCode int = 200

/*FindAccountsUsingGETOK OK

swagger:response findAccountsUsingGETOK
*/
type FindAccountsUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.LatestAccountMappingModel `json:"body,omitempty"`
}

// NewFindAccountsUsingGETOK creates FindAccountsUsingGETOK with default headers values
func NewFindAccountsUsingGETOK() *FindAccountsUsingGETOK {

	return &FindAccountsUsingGETOK{}
}

// WithPayload adds the payload to the find accounts using g e t o k response
func (o *FindAccountsUsingGETOK) WithPayload(payload *models.LatestAccountMappingModel) *FindAccountsUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find accounts using g e t o k response
func (o *FindAccountsUsingGETOK) SetPayload(payload *models.LatestAccountMappingModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindAccountsUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindAccountsUsingGETUnauthorizedCode is the HTTP code returned for type FindAccountsUsingGETUnauthorized
const FindAccountsUsingGETUnauthorizedCode int = 401

/*FindAccountsUsingGETUnauthorized Unauthorized

swagger:response findAccountsUsingGETUnauthorized
*/
type FindAccountsUsingGETUnauthorized struct {
}

// NewFindAccountsUsingGETUnauthorized creates FindAccountsUsingGETUnauthorized with default headers values
func NewFindAccountsUsingGETUnauthorized() *FindAccountsUsingGETUnauthorized {

	return &FindAccountsUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *FindAccountsUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindAccountsUsingGETForbiddenCode is the HTTP code returned for type FindAccountsUsingGETForbidden
const FindAccountsUsingGETForbiddenCode int = 403

/*FindAccountsUsingGETForbidden Forbidden

swagger:response findAccountsUsingGETForbidden
*/
type FindAccountsUsingGETForbidden struct {
}

// NewFindAccountsUsingGETForbidden creates FindAccountsUsingGETForbidden with default headers values
func NewFindAccountsUsingGETForbidden() *FindAccountsUsingGETForbidden {

	return &FindAccountsUsingGETForbidden{}
}

// WriteResponse to the client
func (o *FindAccountsUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindAccountsUsingGETNotFoundCode is the HTTP code returned for type FindAccountsUsingGETNotFound
const FindAccountsUsingGETNotFoundCode int = 404

/*FindAccountsUsingGETNotFound Not Found

swagger:response findAccountsUsingGETNotFound
*/
type FindAccountsUsingGETNotFound struct {
}

// NewFindAccountsUsingGETNotFound creates FindAccountsUsingGETNotFound with default headers values
func NewFindAccountsUsingGETNotFound() *FindAccountsUsingGETNotFound {

	return &FindAccountsUsingGETNotFound{}
}

// WriteResponse to the client
func (o *FindAccountsUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
