// Code generated by go-swagger; DO NOT EDIT.

package account_mapping_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// GetAccountUsingGET1OKCode is the HTTP code returned for type GetAccountUsingGET1OK
const GetAccountUsingGET1OKCode int = 200

/*GetAccountUsingGET1OK OK

swagger:response getAccountUsingGET1OK
*/
type GetAccountUsingGET1OK struct {

	/*
	  In: Body
	*/
	Payload *models.AccountMappingModel `json:"body,omitempty"`
}

// NewGetAccountUsingGET1OK creates GetAccountUsingGET1OK with default headers values
func NewGetAccountUsingGET1OK() *GetAccountUsingGET1OK {

	return &GetAccountUsingGET1OK{}
}

// WithPayload adds the payload to the get account using g e t1 o k response
func (o *GetAccountUsingGET1OK) WithPayload(payload *models.AccountMappingModel) *GetAccountUsingGET1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get account using g e t1 o k response
func (o *GetAccountUsingGET1OK) SetPayload(payload *models.AccountMappingModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountUsingGET1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAccountUsingGET1UnauthorizedCode is the HTTP code returned for type GetAccountUsingGET1Unauthorized
const GetAccountUsingGET1UnauthorizedCode int = 401

/*GetAccountUsingGET1Unauthorized Unauthorized

swagger:response getAccountUsingGET1Unauthorized
*/
type GetAccountUsingGET1Unauthorized struct {
}

// NewGetAccountUsingGET1Unauthorized creates GetAccountUsingGET1Unauthorized with default headers values
func NewGetAccountUsingGET1Unauthorized() *GetAccountUsingGET1Unauthorized {

	return &GetAccountUsingGET1Unauthorized{}
}

// WriteResponse to the client
func (o *GetAccountUsingGET1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetAccountUsingGET1ForbiddenCode is the HTTP code returned for type GetAccountUsingGET1Forbidden
const GetAccountUsingGET1ForbiddenCode int = 403

/*GetAccountUsingGET1Forbidden Forbidden

swagger:response getAccountUsingGET1Forbidden
*/
type GetAccountUsingGET1Forbidden struct {
}

// NewGetAccountUsingGET1Forbidden creates GetAccountUsingGET1Forbidden with default headers values
func NewGetAccountUsingGET1Forbidden() *GetAccountUsingGET1Forbidden {

	return &GetAccountUsingGET1Forbidden{}
}

// WriteResponse to the client
func (o *GetAccountUsingGET1Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetAccountUsingGET1NotFoundCode is the HTTP code returned for type GetAccountUsingGET1NotFound
const GetAccountUsingGET1NotFoundCode int = 404

/*GetAccountUsingGET1NotFound Not Found

swagger:response getAccountUsingGET1NotFound
*/
type GetAccountUsingGET1NotFound struct {
}

// NewGetAccountUsingGET1NotFound creates GetAccountUsingGET1NotFound with default headers values
func NewGetAccountUsingGET1NotFound() *GetAccountUsingGET1NotFound {

	return &GetAccountUsingGET1NotFound{}
}

// WriteResponse to the client
func (o *GetAccountUsingGET1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
