// Code generated by go-swagger; DO NOT EDIT.

package erc_777_transfers_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindERC777TransfersUsingGETHandlerFunc turns a function with the right signature into a find e r c777 transfers using g e t handler
type FindERC777TransfersUsingGETHandlerFunc func(FindERC777TransfersUsingGETParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindERC777TransfersUsingGETHandlerFunc) Handle(params FindERC777TransfersUsingGETParams) middleware.Responder {
	return fn(params)
}

// FindERC777TransfersUsingGETHandler interface for that can handle valid find e r c777 transfers using g e t params
type FindERC777TransfersUsingGETHandler interface {
	Handle(FindERC777TransfersUsingGETParams) middleware.Responder
}

// NewFindERC777TransfersUsingGET creates a new http.Handler for the find e r c777 transfers using g e t operation
func NewFindERC777TransfersUsingGET(ctx *middleware.Context, handler FindERC777TransfersUsingGETHandler) *FindERC777TransfersUsingGET {
	return &FindERC777TransfersUsingGET{Context: ctx, Handler: handler}
}

/* FindERC777TransfersUsingGET swagger:route GET /tokens/{addressHash}/erc777/transfers erc-777-transfers-controller findERC777TransfersUsingGET

Retrieve transfers of an ERC777 Token.

*/
type FindERC777TransfersUsingGET struct {
	Context *middleware.Context
	Handler FindERC777TransfersUsingGETHandler
}

func (o *FindERC777TransfersUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFindERC777TransfersUsingGETParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
