// Code generated by go-swagger; DO NOT EDIT.

package dashboard_tokens_totals_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// GetTokenTotalsUsingGETOKCode is the HTTP code returned for type GetTokenTotalsUsingGETOK
const GetTokenTotalsUsingGETOKCode int = 200

/*GetTokenTotalsUsingGETOK OK

swagger:response getTokenTotalsUsingGETOK
*/
type GetTokenTotalsUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.DashboardTotalsModel `json:"body,omitempty"`
}

// NewGetTokenTotalsUsingGETOK creates GetTokenTotalsUsingGETOK with default headers values
func NewGetTokenTotalsUsingGETOK() *GetTokenTotalsUsingGETOK {

	return &GetTokenTotalsUsingGETOK{}
}

// WithPayload adds the payload to the get token totals using g e t o k response
func (o *GetTokenTotalsUsingGETOK) WithPayload(payload *models.DashboardTotalsModel) *GetTokenTotalsUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get token totals using g e t o k response
func (o *GetTokenTotalsUsingGETOK) SetPayload(payload *models.DashboardTotalsModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTokenTotalsUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTokenTotalsUsingGETUnauthorizedCode is the HTTP code returned for type GetTokenTotalsUsingGETUnauthorized
const GetTokenTotalsUsingGETUnauthorizedCode int = 401

/*GetTokenTotalsUsingGETUnauthorized Unauthorized

swagger:response getTokenTotalsUsingGETUnauthorized
*/
type GetTokenTotalsUsingGETUnauthorized struct {
}

// NewGetTokenTotalsUsingGETUnauthorized creates GetTokenTotalsUsingGETUnauthorized with default headers values
func NewGetTokenTotalsUsingGETUnauthorized() *GetTokenTotalsUsingGETUnauthorized {

	return &GetTokenTotalsUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *GetTokenTotalsUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetTokenTotalsUsingGETForbiddenCode is the HTTP code returned for type GetTokenTotalsUsingGETForbidden
const GetTokenTotalsUsingGETForbiddenCode int = 403

/*GetTokenTotalsUsingGETForbidden Forbidden

swagger:response getTokenTotalsUsingGETForbidden
*/
type GetTokenTotalsUsingGETForbidden struct {
}

// NewGetTokenTotalsUsingGETForbidden creates GetTokenTotalsUsingGETForbidden with default headers values
func NewGetTokenTotalsUsingGETForbidden() *GetTokenTotalsUsingGETForbidden {

	return &GetTokenTotalsUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetTokenTotalsUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetTokenTotalsUsingGETNotFoundCode is the HTTP code returned for type GetTokenTotalsUsingGETNotFound
const GetTokenTotalsUsingGETNotFoundCode int = 404

/*GetTokenTotalsUsingGETNotFound Not Found

swagger:response getTokenTotalsUsingGETNotFound
*/
type GetTokenTotalsUsingGETNotFound struct {
}

// NewGetTokenTotalsUsingGETNotFound creates GetTokenTotalsUsingGETNotFound with default headers values
func NewGetTokenTotalsUsingGETNotFound() *GetTokenTotalsUsingGETNotFound {

	return &GetTokenTotalsUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetTokenTotalsUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
