// Code generated by go-swagger; DO NOT EDIT.

package erc_20_transfers_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// FindERC20TransfersUsingGETOKCode is the HTTP code returned for type FindERC20TransfersUsingGETOK
const FindERC20TransfersUsingGETOKCode int = 200

/*FindERC20TransfersUsingGETOK OK

swagger:response findERC20TransfersUsingGETOK
*/
type FindERC20TransfersUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.LatestERC20TransfersModel `json:"body,omitempty"`
}

// NewFindERC20TransfersUsingGETOK creates FindERC20TransfersUsingGETOK with default headers values
func NewFindERC20TransfersUsingGETOK() *FindERC20TransfersUsingGETOK {

	return &FindERC20TransfersUsingGETOK{}
}

// WithPayload adds the payload to the find e r c20 transfers using g e t o k response
func (o *FindERC20TransfersUsingGETOK) WithPayload(payload *models.LatestERC20TransfersModel) *FindERC20TransfersUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find e r c20 transfers using g e t o k response
func (o *FindERC20TransfersUsingGETOK) SetPayload(payload *models.LatestERC20TransfersModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindERC20TransfersUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindERC20TransfersUsingGETUnauthorizedCode is the HTTP code returned for type FindERC20TransfersUsingGETUnauthorized
const FindERC20TransfersUsingGETUnauthorizedCode int = 401

/*FindERC20TransfersUsingGETUnauthorized Unauthorized

swagger:response findERC20TransfersUsingGETUnauthorized
*/
type FindERC20TransfersUsingGETUnauthorized struct {
}

// NewFindERC20TransfersUsingGETUnauthorized creates FindERC20TransfersUsingGETUnauthorized with default headers values
func NewFindERC20TransfersUsingGETUnauthorized() *FindERC20TransfersUsingGETUnauthorized {

	return &FindERC20TransfersUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *FindERC20TransfersUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindERC20TransfersUsingGETForbiddenCode is the HTTP code returned for type FindERC20TransfersUsingGETForbidden
const FindERC20TransfersUsingGETForbiddenCode int = 403

/*FindERC20TransfersUsingGETForbidden Forbidden

swagger:response findERC20TransfersUsingGETForbidden
*/
type FindERC20TransfersUsingGETForbidden struct {
}

// NewFindERC20TransfersUsingGETForbidden creates FindERC20TransfersUsingGETForbidden with default headers values
func NewFindERC20TransfersUsingGETForbidden() *FindERC20TransfersUsingGETForbidden {

	return &FindERC20TransfersUsingGETForbidden{}
}

// WriteResponse to the client
func (o *FindERC20TransfersUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindERC20TransfersUsingGETNotFoundCode is the HTTP code returned for type FindERC20TransfersUsingGETNotFound
const FindERC20TransfersUsingGETNotFoundCode int = 404

/*FindERC20TransfersUsingGETNotFound Not Found

swagger:response findERC20TransfersUsingGETNotFound
*/
type FindERC20TransfersUsingGETNotFound struct {
}

// NewFindERC20TransfersUsingGETNotFound creates FindERC20TransfersUsingGETNotFound with default headers values
func NewFindERC20TransfersUsingGETNotFound() *FindERC20TransfersUsingGETNotFound {

	return &FindERC20TransfersUsingGETNotFound{}
}

// WriteResponse to the client
func (o *FindERC20TransfersUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
