// Code generated by go-swagger; DO NOT EDIT.

package dashboard_totals_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDashboardTotalsUsingGETHandlerFunc turns a function with the right signature into a get dashboard totals using g e t handler
type GetDashboardTotalsUsingGETHandlerFunc func(GetDashboardTotalsUsingGETParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDashboardTotalsUsingGETHandlerFunc) Handle(params GetDashboardTotalsUsingGETParams) middleware.Responder {
	return fn(params)
}

// GetDashboardTotalsUsingGETHandler interface for that can handle valid get dashboard totals using g e t params
type GetDashboardTotalsUsingGETHandler interface {
	Handle(GetDashboardTotalsUsingGETParams) middleware.Responder
}

// NewGetDashboardTotalsUsingGET creates a new http.Handler for the get dashboard totals using g e t operation
func NewGetDashboardTotalsUsingGET(ctx *middleware.Context, handler GetDashboardTotalsUsingGETHandler) *GetDashboardTotalsUsingGET {
	return &GetDashboardTotalsUsingGET{Context: ctx, Handler: handler}
}

/* GetDashboardTotalsUsingGET swagger:route GET /dashboard/totals dashboard-totals-controller getDashboardTotalsUsingGET

Retrieve total number of Contracts, Tokens and Transactions.

*/
type GetDashboardTotalsUsingGET struct {
	Context *middleware.Context
	Handler GetDashboardTotalsUsingGETHandler
}

func (o *GetDashboardTotalsUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDashboardTotalsUsingGETParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
