// Code generated by go-swagger; DO NOT EDIT.

package dashboard_totals_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// GetDashboardTotalsUsingGETOKCode is the HTTP code returned for type GetDashboardTotalsUsingGETOK
const GetDashboardTotalsUsingGETOKCode int = 200

/*GetDashboardTotalsUsingGETOK OK

swagger:response getDashboardTotalsUsingGETOK
*/
type GetDashboardTotalsUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.DashboardTotalsModel `json:"body,omitempty"`
}

// NewGetDashboardTotalsUsingGETOK creates GetDashboardTotalsUsingGETOK with default headers values
func NewGetDashboardTotalsUsingGETOK() *GetDashboardTotalsUsingGETOK {

	return &GetDashboardTotalsUsingGETOK{}
}

// WithPayload adds the payload to the get dashboard totals using g e t o k response
func (o *GetDashboardTotalsUsingGETOK) WithPayload(payload *models.DashboardTotalsModel) *GetDashboardTotalsUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get dashboard totals using g e t o k response
func (o *GetDashboardTotalsUsingGETOK) SetPayload(payload *models.DashboardTotalsModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDashboardTotalsUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDashboardTotalsUsingGETUnauthorizedCode is the HTTP code returned for type GetDashboardTotalsUsingGETUnauthorized
const GetDashboardTotalsUsingGETUnauthorizedCode int = 401

/*GetDashboardTotalsUsingGETUnauthorized Unauthorized

swagger:response getDashboardTotalsUsingGETUnauthorized
*/
type GetDashboardTotalsUsingGETUnauthorized struct {
}

// NewGetDashboardTotalsUsingGETUnauthorized creates GetDashboardTotalsUsingGETUnauthorized with default headers values
func NewGetDashboardTotalsUsingGETUnauthorized() *GetDashboardTotalsUsingGETUnauthorized {

	return &GetDashboardTotalsUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *GetDashboardTotalsUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetDashboardTotalsUsingGETForbiddenCode is the HTTP code returned for type GetDashboardTotalsUsingGETForbidden
const GetDashboardTotalsUsingGETForbiddenCode int = 403

/*GetDashboardTotalsUsingGETForbidden Forbidden

swagger:response getDashboardTotalsUsingGETForbidden
*/
type GetDashboardTotalsUsingGETForbidden struct {
}

// NewGetDashboardTotalsUsingGETForbidden creates GetDashboardTotalsUsingGETForbidden with default headers values
func NewGetDashboardTotalsUsingGETForbidden() *GetDashboardTotalsUsingGETForbidden {

	return &GetDashboardTotalsUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetDashboardTotalsUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetDashboardTotalsUsingGETNotFoundCode is the HTTP code returned for type GetDashboardTotalsUsingGETNotFound
const GetDashboardTotalsUsingGETNotFoundCode int = 404

/*GetDashboardTotalsUsingGETNotFound Not Found

swagger:response getDashboardTotalsUsingGETNotFound
*/
type GetDashboardTotalsUsingGETNotFound struct {
}

// NewGetDashboardTotalsUsingGETNotFound creates GetDashboardTotalsUsingGETNotFound with default headers values
func NewGetDashboardTotalsUsingGETNotFound() *GetDashboardTotalsUsingGETNotFound {

	return &GetDashboardTotalsUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetDashboardTotalsUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
