// Code generated by go-swagger; DO NOT EDIT.

package erc_721_transfers_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// FindERC721TransfersUsingGETOKCode is the HTTP code returned for type FindERC721TransfersUsingGETOK
const FindERC721TransfersUsingGETOKCode int = 200

/*FindERC721TransfersUsingGETOK OK

swagger:response findERC721TransfersUsingGETOK
*/
type FindERC721TransfersUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.LatestERC721TransfersModel `json:"body,omitempty"`
}

// NewFindERC721TransfersUsingGETOK creates FindERC721TransfersUsingGETOK with default headers values
func NewFindERC721TransfersUsingGETOK() *FindERC721TransfersUsingGETOK {

	return &FindERC721TransfersUsingGETOK{}
}

// WithPayload adds the payload to the find e r c721 transfers using g e t o k response
func (o *FindERC721TransfersUsingGETOK) WithPayload(payload *models.LatestERC721TransfersModel) *FindERC721TransfersUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find e r c721 transfers using g e t o k response
func (o *FindERC721TransfersUsingGETOK) SetPayload(payload *models.LatestERC721TransfersModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindERC721TransfersUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindERC721TransfersUsingGETUnauthorizedCode is the HTTP code returned for type FindERC721TransfersUsingGETUnauthorized
const FindERC721TransfersUsingGETUnauthorizedCode int = 401

/*FindERC721TransfersUsingGETUnauthorized Unauthorized

swagger:response findERC721TransfersUsingGETUnauthorized
*/
type FindERC721TransfersUsingGETUnauthorized struct {
}

// NewFindERC721TransfersUsingGETUnauthorized creates FindERC721TransfersUsingGETUnauthorized with default headers values
func NewFindERC721TransfersUsingGETUnauthorized() *FindERC721TransfersUsingGETUnauthorized {

	return &FindERC721TransfersUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *FindERC721TransfersUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindERC721TransfersUsingGETForbiddenCode is the HTTP code returned for type FindERC721TransfersUsingGETForbidden
const FindERC721TransfersUsingGETForbiddenCode int = 403

/*FindERC721TransfersUsingGETForbidden Forbidden

swagger:response findERC721TransfersUsingGETForbidden
*/
type FindERC721TransfersUsingGETForbidden struct {
}

// NewFindERC721TransfersUsingGETForbidden creates FindERC721TransfersUsingGETForbidden with default headers values
func NewFindERC721TransfersUsingGETForbidden() *FindERC721TransfersUsingGETForbidden {

	return &FindERC721TransfersUsingGETForbidden{}
}

// WriteResponse to the client
func (o *FindERC721TransfersUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindERC721TransfersUsingGETNotFoundCode is the HTTP code returned for type FindERC721TransfersUsingGETNotFound
const FindERC721TransfersUsingGETNotFoundCode int = 404

/*FindERC721TransfersUsingGETNotFound Not Found

swagger:response findERC721TransfersUsingGETNotFound
*/
type FindERC721TransfersUsingGETNotFound struct {
}

// NewFindERC721TransfersUsingGETNotFound creates FindERC721TransfersUsingGETNotFound with default headers values
func NewFindERC721TransfersUsingGETNotFound() *FindERC721TransfersUsingGETNotFound {

	return &FindERC721TransfersUsingGETNotFound{}
}

// WriteResponse to the client
func (o *FindERC721TransfersUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
