// Code generated by go-swagger; DO NOT EDIT.

package token_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// FindTokensUsingGETOKCode is the HTTP code returned for type FindTokensUsingGETOK
const FindTokensUsingGETOKCode int = 200

/*FindTokensUsingGETOK OK

swagger:response findTokensUsingGETOK
*/
type FindTokensUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListTokenModel `json:"body,omitempty"`
}

// NewFindTokensUsingGETOK creates FindTokensUsingGETOK with default headers values
func NewFindTokensUsingGETOK() *FindTokensUsingGETOK {

	return &FindTokensUsingGETOK{}
}

// WithPayload adds the payload to the find tokens using g e t o k response
func (o *FindTokensUsingGETOK) WithPayload(payload *models.ListTokenModel) *FindTokensUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find tokens using g e t o k response
func (o *FindTokensUsingGETOK) SetPayload(payload *models.ListTokenModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindTokensUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindTokensUsingGETUnauthorizedCode is the HTTP code returned for type FindTokensUsingGETUnauthorized
const FindTokensUsingGETUnauthorizedCode int = 401

/*FindTokensUsingGETUnauthorized Unauthorized

swagger:response findTokensUsingGETUnauthorized
*/
type FindTokensUsingGETUnauthorized struct {
}

// NewFindTokensUsingGETUnauthorized creates FindTokensUsingGETUnauthorized with default headers values
func NewFindTokensUsingGETUnauthorized() *FindTokensUsingGETUnauthorized {

	return &FindTokensUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *FindTokensUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindTokensUsingGETForbiddenCode is the HTTP code returned for type FindTokensUsingGETForbidden
const FindTokensUsingGETForbiddenCode int = 403

/*FindTokensUsingGETForbidden Forbidden

swagger:response findTokensUsingGETForbidden
*/
type FindTokensUsingGETForbidden struct {
}

// NewFindTokensUsingGETForbidden creates FindTokensUsingGETForbidden with default headers values
func NewFindTokensUsingGETForbidden() *FindTokensUsingGETForbidden {

	return &FindTokensUsingGETForbidden{}
}

// WriteResponse to the client
func (o *FindTokensUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindTokensUsingGETNotFoundCode is the HTTP code returned for type FindTokensUsingGETNotFound
const FindTokensUsingGETNotFoundCode int = 404

/*FindTokensUsingGETNotFound Not Found

swagger:response findTokensUsingGETNotFound
*/
type FindTokensUsingGETNotFound struct {
}

// NewFindTokensUsingGETNotFound creates FindTokensUsingGETNotFound with default headers values
func NewFindTokensUsingGETNotFound() *FindTokensUsingGETNotFound {

	return &FindTokensUsingGETNotFound{}
}

// WriteResponse to the client
func (o *FindTokensUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
