// Code generated by go-swagger; DO NOT EDIT.

package token_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// GetTokenUsingGETOKCode is the HTTP code returned for type GetTokenUsingGETOK
const GetTokenUsingGETOKCode int = 200

/*GetTokenUsingGETOK OK

swagger:response getTokenUsingGETOK
*/
type GetTokenUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.TokenModel `json:"body,omitempty"`
}

// NewGetTokenUsingGETOK creates GetTokenUsingGETOK with default headers values
func NewGetTokenUsingGETOK() *GetTokenUsingGETOK {

	return &GetTokenUsingGETOK{}
}

// WithPayload adds the payload to the get token using g e t o k response
func (o *GetTokenUsingGETOK) WithPayload(payload *models.TokenModel) *GetTokenUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get token using g e t o k response
func (o *GetTokenUsingGETOK) SetPayload(payload *models.TokenModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTokenUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTokenUsingGETUnauthorizedCode is the HTTP code returned for type GetTokenUsingGETUnauthorized
const GetTokenUsingGETUnauthorizedCode int = 401

/*GetTokenUsingGETUnauthorized Unauthorized

swagger:response getTokenUsingGETUnauthorized
*/
type GetTokenUsingGETUnauthorized struct {
}

// NewGetTokenUsingGETUnauthorized creates GetTokenUsingGETUnauthorized with default headers values
func NewGetTokenUsingGETUnauthorized() *GetTokenUsingGETUnauthorized {

	return &GetTokenUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *GetTokenUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetTokenUsingGETForbiddenCode is the HTTP code returned for type GetTokenUsingGETForbidden
const GetTokenUsingGETForbiddenCode int = 403

/*GetTokenUsingGETForbidden Forbidden

swagger:response getTokenUsingGETForbidden
*/
type GetTokenUsingGETForbidden struct {
}

// NewGetTokenUsingGETForbidden creates GetTokenUsingGETForbidden with default headers values
func NewGetTokenUsingGETForbidden() *GetTokenUsingGETForbidden {

	return &GetTokenUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetTokenUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetTokenUsingGETNotFoundCode is the HTTP code returned for type GetTokenUsingGETNotFound
const GetTokenUsingGETNotFoundCode int = 404

/*GetTokenUsingGETNotFound Not Found

swagger:response getTokenUsingGETNotFound
*/
type GetTokenUsingGETNotFound struct {
}

// NewGetTokenUsingGETNotFound creates GetTokenUsingGETNotFound with default headers values
func NewGetTokenUsingGETNotFound() *GetTokenUsingGETNotFound {

	return &GetTokenUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetTokenUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
