// Code generated by go-swagger; DO NOT EDIT.

package index_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// HomePageUsingGETOKCode is the HTTP code returned for type HomePageUsingGETOK
const HomePageUsingGETOKCode int = 200

/*HomePageUsingGETOK OK

swagger:response homePageUsingGETOK
*/
type HomePageUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewHomePageUsingGETOK creates HomePageUsingGETOK with default headers values
func NewHomePageUsingGETOK() *HomePageUsingGETOK {

	return &HomePageUsingGETOK{}
}

// WithPayload adds the payload to the home page using g e t o k response
func (o *HomePageUsingGETOK) WithPayload(payload string) *HomePageUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the home page using g e t o k response
func (o *HomePageUsingGETOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HomePageUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// HomePageUsingGETUnauthorizedCode is the HTTP code returned for type HomePageUsingGETUnauthorized
const HomePageUsingGETUnauthorizedCode int = 401

/*HomePageUsingGETUnauthorized Unauthorized

swagger:response homePageUsingGETUnauthorized
*/
type HomePageUsingGETUnauthorized struct {
}

// NewHomePageUsingGETUnauthorized creates HomePageUsingGETUnauthorized with default headers values
func NewHomePageUsingGETUnauthorized() *HomePageUsingGETUnauthorized {

	return &HomePageUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *HomePageUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// HomePageUsingGETForbiddenCode is the HTTP code returned for type HomePageUsingGETForbidden
const HomePageUsingGETForbiddenCode int = 403

/*HomePageUsingGETForbidden Forbidden

swagger:response homePageUsingGETForbidden
*/
type HomePageUsingGETForbidden struct {
}

// NewHomePageUsingGETForbidden creates HomePageUsingGETForbidden with default headers values
func NewHomePageUsingGETForbidden() *HomePageUsingGETForbidden {

	return &HomePageUsingGETForbidden{}
}

// WriteResponse to the client
func (o *HomePageUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// HomePageUsingGETNotFoundCode is the HTTP code returned for type HomePageUsingGETNotFound
const HomePageUsingGETNotFoundCode int = 404

/*HomePageUsingGETNotFound Not Found

swagger:response homePageUsingGETNotFound
*/
type HomePageUsingGETNotFound struct {
}

// NewHomePageUsingGETNotFound creates HomePageUsingGETNotFound with default headers values
func NewHomePageUsingGETNotFound() *HomePageUsingGETNotFound {

	return &HomePageUsingGETNotFound{}
}

// WriteResponse to the client
func (o *HomePageUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
