// Code generated by go-swagger; DO NOT EDIT.

package index_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewHomePageUsingGETParams creates a new HomePageUsingGETParams object
//
// There are no default values defined in the spec.
func NewHomePageUsingGETParams() HomePageUsingGETParams {

	return HomePageUsingGETParams{}
}

// HomePageUsingGETParams contains all the bound params for the home page using g e t operation
// typically these are obtained from a http.Request
//
// swagger:parameters homePageUsingGET
type HomePageUsingGETParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewHomePageUsingGETParams() beforehand.
func (o *HomePageUsingGETParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
