// Code generated by go-swagger; DO NOT EDIT.

package index_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// IndexUsingGETOKCode is the HTTP code returned for type IndexUsingGETOK
const IndexUsingGETOKCode int = 200

/*IndexUsingGETOK OK

swagger:response indexUsingGETOK
*/
type IndexUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.Jwt `json:"body,omitempty"`
}

// NewIndexUsingGETOK creates IndexUsingGETOK with default headers values
func NewIndexUsingGETOK() *IndexUsingGETOK {

	return &IndexUsingGETOK{}
}

// WithPayload adds the payload to the index using g e t o k response
func (o *IndexUsingGETOK) WithPayload(payload *models.Jwt) *IndexUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the index using g e t o k response
func (o *IndexUsingGETOK) SetPayload(payload *models.Jwt) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IndexUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// IndexUsingGETUnauthorizedCode is the HTTP code returned for type IndexUsingGETUnauthorized
const IndexUsingGETUnauthorizedCode int = 401

/*IndexUsingGETUnauthorized Unauthorized

swagger:response indexUsingGETUnauthorized
*/
type IndexUsingGETUnauthorized struct {
}

// NewIndexUsingGETUnauthorized creates IndexUsingGETUnauthorized with default headers values
func NewIndexUsingGETUnauthorized() *IndexUsingGETUnauthorized {

	return &IndexUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *IndexUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// IndexUsingGETForbiddenCode is the HTTP code returned for type IndexUsingGETForbidden
const IndexUsingGETForbiddenCode int = 403

/*IndexUsingGETForbidden Forbidden

swagger:response indexUsingGETForbidden
*/
type IndexUsingGETForbidden struct {
}

// NewIndexUsingGETForbidden creates IndexUsingGETForbidden with default headers values
func NewIndexUsingGETForbidden() *IndexUsingGETForbidden {

	return &IndexUsingGETForbidden{}
}

// WriteResponse to the client
func (o *IndexUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// IndexUsingGETNotFoundCode is the HTTP code returned for type IndexUsingGETNotFound
const IndexUsingGETNotFoundCode int = 404

/*IndexUsingGETNotFound Not Found

swagger:response indexUsingGETNotFound
*/
type IndexUsingGETNotFound struct {
}

// NewIndexUsingGETNotFound creates IndexUsingGETNotFound with default headers values
func NewIndexUsingGETNotFound() *IndexUsingGETNotFound {

	return &IndexUsingGETNotFound{}
}

// WriteResponse to the client
func (o *IndexUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
