// Code generated by go-swagger; DO NOT EDIT.

package contract_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetContractUsingGETParams creates a new GetContractUsingGETParams object
//
// There are no default values defined in the spec.
func NewGetContractUsingGETParams() GetContractUsingGETParams {

	return GetContractUsingGETParams{}
}

// GetContractUsingGETParams contains all the bound params for the get contract using g e t operation
// typically these are obtained from a http.Request
//
// swagger:parameters getContractUsingGET
type GetContractUsingGETParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The address hash identifying the contract.
	  In: path
	*/
	AddressHash *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetContractUsingGETParams() beforehand.
func (o *GetContractUsingGETParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rAddressHash, rhkAddressHash, _ := route.Params.GetOK("addressHash")
	if err := o.bindAddressHash(rAddressHash, rhkAddressHash, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAddressHash binds and validates parameter AddressHash from path.
func (o *GetContractUsingGETParams) bindAddressHash(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// Parameter is provided by construction from the route
	o.AddressHash = &raw

	return nil
}
