// Code generated by go-swagger; DO NOT EDIT.

package contract_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// GetContractUsingGETOKCode is the HTTP code returned for type GetContractUsingGETOK
const GetContractUsingGETOKCode int = 200

/*GetContractUsingGETOK OK

swagger:response getContractUsingGETOK
*/
type GetContractUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.ContractModel `json:"body,omitempty"`
}

// NewGetContractUsingGETOK creates GetContractUsingGETOK with default headers values
func NewGetContractUsingGETOK() *GetContractUsingGETOK {

	return &GetContractUsingGETOK{}
}

// WithPayload adds the payload to the get contract using g e t o k response
func (o *GetContractUsingGETOK) WithPayload(payload *models.ContractModel) *GetContractUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get contract using g e t o k response
func (o *GetContractUsingGETOK) SetPayload(payload *models.ContractModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContractUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetContractUsingGETUnauthorizedCode is the HTTP code returned for type GetContractUsingGETUnauthorized
const GetContractUsingGETUnauthorizedCode int = 401

/*GetContractUsingGETUnauthorized Unauthorized

swagger:response getContractUsingGETUnauthorized
*/
type GetContractUsingGETUnauthorized struct {
}

// NewGetContractUsingGETUnauthorized creates GetContractUsingGETUnauthorized with default headers values
func NewGetContractUsingGETUnauthorized() *GetContractUsingGETUnauthorized {

	return &GetContractUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *GetContractUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetContractUsingGETForbiddenCode is the HTTP code returned for type GetContractUsingGETForbidden
const GetContractUsingGETForbiddenCode int = 403

/*GetContractUsingGETForbidden Forbidden

swagger:response getContractUsingGETForbidden
*/
type GetContractUsingGETForbidden struct {
}

// NewGetContractUsingGETForbidden creates GetContractUsingGETForbidden with default headers values
func NewGetContractUsingGETForbidden() *GetContractUsingGETForbidden {

	return &GetContractUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetContractUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetContractUsingGETNotFoundCode is the HTTP code returned for type GetContractUsingGETNotFound
const GetContractUsingGETNotFoundCode int = 404

/*GetContractUsingGETNotFound Not Found

swagger:response getContractUsingGETNotFound
*/
type GetContractUsingGETNotFound struct {
}

// NewGetContractUsingGETNotFound creates GetContractUsingGETNotFound with default headers values
func NewGetContractUsingGETNotFound() *GetContractUsingGETNotFound {

	return &GetContractUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetContractUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
