// Code generated by go-swagger; DO NOT EDIT.

package gas_oracle_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GasPriceInfoUsingGETHandlerFunc turns a function with the right signature into a gas price info using g e t handler
type GasPriceInfoUsingGETHandlerFunc func(GasPriceInfoUsingGETParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GasPriceInfoUsingGETHandlerFunc) Handle(params GasPriceInfoUsingGETParams) middleware.Responder {
	return fn(params)
}

// GasPriceInfoUsingGETHandler interface for that can handle valid gas price info using g e t params
type GasPriceInfoUsingGETHandler interface {
	Handle(GasPriceInfoUsingGETParams) middleware.Responder
}

// NewGasPriceInfoUsingGET creates a new http.Handler for the gas price info using g e t operation
func NewGasPriceInfoUsingGET(ctx *middleware.Context, handler GasPriceInfoUsingGETHandler) *GasPriceInfoUsingGET {
	return &GasPriceInfoUsingGET{Context: ctx, Handler: handler}
}

/* GasPriceInfoUsingGET swagger:route GET /gas/price gas-oracle-controller gasPriceInfoUsingGET

Gas price oracle.

*/
type GasPriceInfoUsingGET struct {
	Context *middleware.Context
	Handler GasPriceInfoUsingGETHandler
}

func (o *GasPriceInfoUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGasPriceInfoUsingGETParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
