// Code generated by go-swagger; DO NOT EDIT.

package account_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// GetAccountUsingGETOKCode is the HTTP code returned for type GetAccountUsingGETOK
const GetAccountUsingGETOKCode int = 200

/*GetAccountUsingGETOK OK

swagger:response getAccountUsingGETOK
*/
type GetAccountUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.AccountModel `json:"body,omitempty"`
}

// NewGetAccountUsingGETOK creates GetAccountUsingGETOK with default headers values
func NewGetAccountUsingGETOK() *GetAccountUsingGETOK {

	return &GetAccountUsingGETOK{}
}

// WithPayload adds the payload to the get account using g e t o k response
func (o *GetAccountUsingGETOK) WithPayload(payload *models.AccountModel) *GetAccountUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get account using g e t o k response
func (o *GetAccountUsingGETOK) SetPayload(payload *models.AccountModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAccountUsingGETUnauthorizedCode is the HTTP code returned for type GetAccountUsingGETUnauthorized
const GetAccountUsingGETUnauthorizedCode int = 401

/*GetAccountUsingGETUnauthorized Unauthorized

swagger:response getAccountUsingGETUnauthorized
*/
type GetAccountUsingGETUnauthorized struct {
}

// NewGetAccountUsingGETUnauthorized creates GetAccountUsingGETUnauthorized with default headers values
func NewGetAccountUsingGETUnauthorized() *GetAccountUsingGETUnauthorized {

	return &GetAccountUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *GetAccountUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetAccountUsingGETForbiddenCode is the HTTP code returned for type GetAccountUsingGETForbidden
const GetAccountUsingGETForbiddenCode int = 403

/*GetAccountUsingGETForbidden Forbidden

swagger:response getAccountUsingGETForbidden
*/
type GetAccountUsingGETForbidden struct {
}

// NewGetAccountUsingGETForbidden creates GetAccountUsingGETForbidden with default headers values
func NewGetAccountUsingGETForbidden() *GetAccountUsingGETForbidden {

	return &GetAccountUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetAccountUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetAccountUsingGETNotFoundCode is the HTTP code returned for type GetAccountUsingGETNotFound
const GetAccountUsingGETNotFoundCode int = 404

/*GetAccountUsingGETNotFound Not Found

swagger:response getAccountUsingGETNotFound
*/
type GetAccountUsingGETNotFound struct {
}

// NewGetAccountUsingGETNotFound creates GetAccountUsingGETNotFound with default headers values
func NewGetAccountUsingGETNotFound() *GetAccountUsingGETNotFound {

	return &GetAccountUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetAccountUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
