// Code generated by go-swagger; DO NOT EDIT.

package token_events_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// GetTokenEventsUsingGETOKCode is the HTTP code returned for type GetTokenEventsUsingGETOK
const GetTokenEventsUsingGETOKCode int = 200

/*GetTokenEventsUsingGETOK OK

swagger:response getTokenEventsUsingGETOK
*/
type GetTokenEventsUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.EventsModel `json:"body,omitempty"`
}

// NewGetTokenEventsUsingGETOK creates GetTokenEventsUsingGETOK with default headers values
func NewGetTokenEventsUsingGETOK() *GetTokenEventsUsingGETOK {

	return &GetTokenEventsUsingGETOK{}
}

// WithPayload adds the payload to the get token events using g e t o k response
func (o *GetTokenEventsUsingGETOK) WithPayload(payload *models.EventsModel) *GetTokenEventsUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get token events using g e t o k response
func (o *GetTokenEventsUsingGETOK) SetPayload(payload *models.EventsModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTokenEventsUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTokenEventsUsingGETUnauthorizedCode is the HTTP code returned for type GetTokenEventsUsingGETUnauthorized
const GetTokenEventsUsingGETUnauthorizedCode int = 401

/*GetTokenEventsUsingGETUnauthorized Unauthorized

swagger:response getTokenEventsUsingGETUnauthorized
*/
type GetTokenEventsUsingGETUnauthorized struct {
}

// NewGetTokenEventsUsingGETUnauthorized creates GetTokenEventsUsingGETUnauthorized with default headers values
func NewGetTokenEventsUsingGETUnauthorized() *GetTokenEventsUsingGETUnauthorized {

	return &GetTokenEventsUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *GetTokenEventsUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetTokenEventsUsingGETForbiddenCode is the HTTP code returned for type GetTokenEventsUsingGETForbidden
const GetTokenEventsUsingGETForbiddenCode int = 403

/*GetTokenEventsUsingGETForbidden Forbidden

swagger:response getTokenEventsUsingGETForbidden
*/
type GetTokenEventsUsingGETForbidden struct {
}

// NewGetTokenEventsUsingGETForbidden creates GetTokenEventsUsingGETForbidden with default headers values
func NewGetTokenEventsUsingGETForbidden() *GetTokenEventsUsingGETForbidden {

	return &GetTokenEventsUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetTokenEventsUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetTokenEventsUsingGETNotFoundCode is the HTTP code returned for type GetTokenEventsUsingGETNotFound
const GetTokenEventsUsingGETNotFoundCode int = 404

/*GetTokenEventsUsingGETNotFound Not Found

swagger:response getTokenEventsUsingGETNotFound
*/
type GetTokenEventsUsingGETNotFound struct {
}

// NewGetTokenEventsUsingGETNotFound creates GetTokenEventsUsingGETNotFound with default headers values
func NewGetTokenEventsUsingGETNotFound() *GetTokenEventsUsingGETNotFound {

	return &GetTokenEventsUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetTokenEventsUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
