// Code generated by go-swagger; DO NOT EDIT.

package account_transactions_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dcn_sdk/models"
)

// FindAccountTransactionsUsingGETOKCode is the HTTP code returned for type FindAccountTransactionsUsingGETOK
const FindAccountTransactionsUsingGETOKCode int = 200

/*FindAccountTransactionsUsingGETOK OK

swagger:response findAccountTransactionsUsingGETOK
*/
type FindAccountTransactionsUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.LatestTransactionModel `json:"body,omitempty"`
}

// NewFindAccountTransactionsUsingGETOK creates FindAccountTransactionsUsingGETOK with default headers values
func NewFindAccountTransactionsUsingGETOK() *FindAccountTransactionsUsingGETOK {

	return &FindAccountTransactionsUsingGETOK{}
}

// WithPayload adds the payload to the find account transactions using g e t o k response
func (o *FindAccountTransactionsUsingGETOK) WithPayload(payload *models.LatestTransactionModel) *FindAccountTransactionsUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find account transactions using g e t o k response
func (o *FindAccountTransactionsUsingGETOK) SetPayload(payload *models.LatestTransactionModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindAccountTransactionsUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindAccountTransactionsUsingGETUnauthorizedCode is the HTTP code returned for type FindAccountTransactionsUsingGETUnauthorized
const FindAccountTransactionsUsingGETUnauthorizedCode int = 401

/*FindAccountTransactionsUsingGETUnauthorized Unauthorized

swagger:response findAccountTransactionsUsingGETUnauthorized
*/
type FindAccountTransactionsUsingGETUnauthorized struct {
}

// NewFindAccountTransactionsUsingGETUnauthorized creates FindAccountTransactionsUsingGETUnauthorized with default headers values
func NewFindAccountTransactionsUsingGETUnauthorized() *FindAccountTransactionsUsingGETUnauthorized {

	return &FindAccountTransactionsUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *FindAccountTransactionsUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindAccountTransactionsUsingGETForbiddenCode is the HTTP code returned for type FindAccountTransactionsUsingGETForbidden
const FindAccountTransactionsUsingGETForbiddenCode int = 403

/*FindAccountTransactionsUsingGETForbidden Forbidden

swagger:response findAccountTransactionsUsingGETForbidden
*/
type FindAccountTransactionsUsingGETForbidden struct {
}

// NewFindAccountTransactionsUsingGETForbidden creates FindAccountTransactionsUsingGETForbidden with default headers values
func NewFindAccountTransactionsUsingGETForbidden() *FindAccountTransactionsUsingGETForbidden {

	return &FindAccountTransactionsUsingGETForbidden{}
}

// WriteResponse to the client
func (o *FindAccountTransactionsUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindAccountTransactionsUsingGETNotFoundCode is the HTTP code returned for type FindAccountTransactionsUsingGETNotFound
const FindAccountTransactionsUsingGETNotFoundCode int = 404

/*FindAccountTransactionsUsingGETNotFound Not Found

swagger:response findAccountTransactionsUsingGETNotFound
*/
type FindAccountTransactionsUsingGETNotFound struct {
}

// NewFindAccountTransactionsUsingGETNotFound creates FindAccountTransactionsUsingGETNotFound with default headers values
func NewFindAccountTransactionsUsingGETNotFound() *FindAccountTransactionsUsingGETNotFound {

	return &FindAccountTransactionsUsingGETNotFound{}
}

// WriteResponse to the client
func (o *FindAccountTransactionsUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
