// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EpirusConfigurationModel EpirusConfigurationModel
//
// swagger:model EpirusConfigurationModel
type EpirusConfigurationModel struct {

	// logo Url
	// Required: true
	LogoURL *string `json:"logoUrl"`
}

// Validate validates this epirus configuration model
func (m *EpirusConfigurationModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLogoURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EpirusConfigurationModel) validateLogoURL(formats strfmt.Registry) error {

	if err := validate.Required("logoUrl", "body", m.LogoURL); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this epirus configuration model based on context it is used
func (m *EpirusConfigurationModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EpirusConfigurationModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EpirusConfigurationModel) UnmarshalBinary(b []byte) error {
	var res EpirusConfigurationModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
