// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GasPriceModel GasPriceModel
//
// swagger:model GasPriceModel
type GasPriceModel struct {

	// gas price
	// Required: true
	GasPrice *float64 `json:"gasPrice"`

	// high
	// Required: true
	High *float64 `json:"high"`

	// safe low
	// Required: true
	SafeLow *float64 `json:"safeLow"`
}

// Validate validates this gas price model
func (m *GasPriceModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGasPrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHigh(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSafeLow(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GasPriceModel) validateGasPrice(formats strfmt.Registry) error {

	if err := validate.Required("gasPrice", "body", m.GasPrice); err != nil {
		return err
	}

	return nil
}

func (m *GasPriceModel) validateHigh(formats strfmt.Registry) error {

	if err := validate.Required("high", "body", m.High); err != nil {
		return err
	}

	return nil
}

func (m *GasPriceModel) validateSafeLow(formats strfmt.Registry) error {

	if err := validate.Required("safeLow", "body", m.SafeLow); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this gas price model based on context it is used
func (m *GasPriceModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GasPriceModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GasPriceModel) UnmarshalBinary(b []byte) error {
	var res GasPriceModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
