// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Log Log
//
// swagger:model Log
type Log struct {

	// address
	Address string `json:"address,omitempty"`

	// block hash
	BlockHash string `json:"blockHash,omitempty"`

	// block number
	BlockNumber int64 `json:"blockNumber,omitempty"`

	// block number raw
	BlockNumberRaw string `json:"blockNumberRaw,omitempty"`

	// data
	Data string `json:"data,omitempty"`

	// log index
	LogIndex int64 `json:"logIndex,omitempty"`

	// log index raw
	LogIndexRaw string `json:"logIndexRaw,omitempty"`

	// removed
	Removed bool `json:"removed,omitempty"`

	// topics
	Topics []string `json:"topics"`

	// transaction hash
	TransactionHash string `json:"transactionHash,omitempty"`

	// transaction index
	TransactionIndex int64 `json:"transactionIndex,omitempty"`

	// transaction index raw
	TransactionIndexRaw string `json:"transactionIndexRaw,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this log
func (m *Log) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this log based on context it is used
func (m *Log) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Log) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Log) UnmarshalBinary(b []byte) error {
	var res Log
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
